AWSTemplateFormatVersion: "2010-09-09"
Description: "LMR — S3 Buckets"

Parameters:
  Environment:
    Type: String

Resources:
  DataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "lmr-data-cogs-${Environment}"
      NotificationConfiguration:
        EventBridgeConfiguration:
          EventBridgeEnabled: true
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: TransitionToIA
            Status: Enabled
            Transitions:
              - StorageClass: STANDARD_IA
                TransitionInDays: 90

Outputs:
  DataBucketName:
    Value: !Ref DataBucket
  DataBucketArn:
    Value: !GetAtt DataBucket.Arn
